class Board:
    cells: list[int]
    black_to_move: bool

    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def is_legal(self, idx: int) -> bool: ...
    def legal_moves(self) -> list[int]: ...
    def play(self, idx: int) -> int: ...  # returns stones flipped, may raise ValueError
    def counts(self) -> tuple[int, int]: ...
    def as_list(self) -> list[int]: ...
    def get_black_to_move(self) -> bool: ...
